language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - printf "\n" | pecl install apcu-beta; echo 'apc.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - ant composer-update
  - ant run-all-tests

notifications:
  email: false
